ALTER TABLE "User" ADD COLUMN "aiTokenPlan" TEXT NOT NULL DEFAULT 'standard';
ALTER TABLE "User" ADD COLUMN "aiTokensUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiTokensResetAt" DATETIME NOT NULL DEFAULT '1970-01-01T00:00:00.000Z';
UPDATE "User" SET "aiTokensResetAt" = CURRENT_TIMESTAMP WHERE "aiTokensResetAt" = '1970-01-01T00:00:00.000Z';
